### ISSUE TITLE
ERR

### ISSUE THREAD

**Issue by houtacheng** [airbenich/multiviewTouchControl#1]
~/multiviewTouchControl  npm install                                                                                                  ✔  17:57:32

npm ERR! code EJSONPARSE
npm ERR! file /Users/sunda/multiviewTouchControl/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token ] in JSON at position 433 while parsing near '...en",
npm ERR! JSON.parse     "touch",
npm ERR! JSON.parse   ],
npm ERR! JSON.parse   "author": "airb...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

**Comment by airbenich** [comment]
Fixed issue in 
https://github.com/airbenich/multiviewTouchControl/commit/2f612e88b22f8e7094bad4dec1487eae426be91e
