### ISSUE TITLE
isues due to nodejs v10

### ISSUE THREAD

**Issue by soundpartner** [airbenich/multiviewTouchControl#4]
i just bought a raspberry pi to try this. 
have instaled raspberian, and try to run this. i get an error due to nodejs. it asks me to install a newer nodejs 

`pi@raspberrypi:~/multiviewTouchControl $ npm start 
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> multiviewTouchControl@0.1.0 start /home/pi/multiviewTouchControl
> electron .

(electron:952): Gtk-WARNING **: 22:48:45.916: cannot open display: 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiviewTouchControl@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multiviewTouchControl@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-06-13T20_48_45_976Z-debug.log`
when trying to install nodejs 9

`================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 9.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium"
   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium" (recommended)
   * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...

## Populating apt-get cache...

+ apt-get update
Havde:1 http://archive.raspberrypi.org/debian buster InRelease
Havde:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Indlæser pakkelisterne... Færdig

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 9.x repo...

+ echo 'deb https://deb.nodesource.com/node_9.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_9.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Havde:1 http://archive.raspberrypi.org/debian buster InRelease
Havde:2 http://raspbian.raspberrypi.org/raspbian buster InRelease        
Henter:3 https://deb.nodesource.com/node_9.x buster InRelease [4.622 B]  
Henter:4 https://deb.nodesource.com/node_9.x buster/main armhf Packages [762 B]
Hentede 5.384 B på 4s (1.516 B/s) 
Indlæser pakkelisterne... Færdig

## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

pi@raspberrypi:~/multiviewTouchControl $node --version
v10.21.0
`

but i keep on having 10.21.0 and cant get it to work.

**Comment by airbenich** [comment]
It looks like your current installed npm is not compatible with the Node.js version you are using. You’ll probably need to update your npm using `npm install stable`

**Comment by soundpartner** [comment]
So got a little closer but still have problems.

here is the logfile

<0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/pi/.nvm/versions/node/v14.4.0/bin/node',
1 verbose cli   '/home/pi/.nvm/versions/node/v14.4.0/bin/npm',
1 verbose cli   'start',
1 verbose cli   'switcher',
1 verbose cli   '192.168.88.3'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle multiviewTouchControl@0.1.0~prestart: multiviewTouchControl@0.1.0
6 info lifecycle multiviewTouchControl@0.1.0~start: multiviewTouchControl@0.1.0
7 verbose lifecycle multiviewTouchControl@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle multiviewTouchControl@0.1.0~start: PATH: /home/pi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/multiviewTouchC$
9 verbose lifecycle multiviewTouchControl@0.1.0~start: CWD: /home/pi/multiviewTouchControl
10 silly lifecycle multiviewTouchControl@0.1.0~start: Args: [ '-c', 'electron . "switcher" "192.168.88.3"' ]
11 silly lifecycle multiviewTouchControl@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle multiviewTouchControl@0.1.0~start: Failed to exec start script
13 verbose stack Error: multiviewTouchControl@0.1.0 start: `electron . "switcher" "192.168.88.3"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/pi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid multiviewTouchControl@0.1.0
15 verbose cwd /home/pi/multiviewTouchControl
16 verbose Linux 4.19.118-v7+
17 verbose argv "/home/pi/.nvm/versions/node/v14.4.0/bin/node" "/home/pi/.nvm/versions/node/v14.4.0/bin/npm" "start" "switcher" "192.168.88.3"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error multiviewTouchControl@0.1.0 start: `electron . "switcher" "192.168.88.3"`
22 error Exit status 1
23 error Failed at the multiviewTouchControl@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]>

**Comment by airbenich** [comment]
Please make a clean clone and try again. Don't forget to do an `npm install`. Make sure to run this on a Mac or linux system.
