### ISSUE TITLE
still problems

### ISSUE THREAD

**Issue by soundpartner** [airbenich/multiviewTouchControl#5]
So got a little closer but still have problems.

here is the logfile

<0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli '/home/pi/.nvm/versions/node/v14.4.0/bin/node',
1 verbose cli '/home/pi/.nvm/versions/node/v14.4.0/bin/npm',
1 verbose cli 'start',
1 verbose cli 'switcher',
1 verbose cli '192.168.88.3'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle multiviewTouchControl@0.1.0prestart: multiviewTouchControl@0.1.0
6 info lifecycle multiviewTouchControl@0.1.0start: multiviewTouchControl@0.1.0
7 verbose lifecycle multiviewTouchControl@0.1.0start: unsafe-perm in lifecycle true
8 verbose lifecycle multiviewTouchControl@0.1.0start: PATH: /home/pi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/multiviewTouchC$
9 verbose lifecycle multiviewTouchControl@0.1.0start: CWD: /home/pi/multiviewTouchControl
10 silly lifecycle multiviewTouchControl@0.1.0start: Args: [ '-c', 'electron . "switcher" "192.168.88.3"' ]
11 silly lifecycle multiviewTouchControl@0.1.0start: Returned: code: 1 signal: null
12 info lifecycle multiviewTouchControl@0.1.0start: Failed to exec start script
13 verbose stack Error: multiviewTouchControl@0.1.0 start: electron . "switcher" "192.168.88.3"
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/home/pi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:315:20)
13 verbose stack at ChildProcess. (/home/pi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:315:20)
13 verbose stack at maybeClose (internal/child_process.js:1051:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid multiviewTouchControl@0.1.0
15 verbose cwd /home/pi/multiviewTouchControl
16 verbose Linux 4.19.118-v7+
17 verbose argv "/home/pi/.nvm/versions/node/v14.4.0/bin/node" "/home/pi/.nvm/versions/node/v14.4.0/bin/npm" "start" "switcher" "192.168.88.3"
18 verbose node v14.4.0
19 verbose npm v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error multiviewTouchControl@0.1.0 start: electron . "switcher" "192.168.88.3"
22 error Exit status 1
23 error Failed at the multiviewTouchControl@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]>

@soundpartner
 
 
Leave a comment

**Comment by soundpartner** [comment]
would it be posible to create a image to transfere directly to a sc-card where it is installed (and working) as the only thing... it would make it a lot easyer for people to use it

**Comment by airbenich** [comment]
Please make a clean clone and try again. Don't forget to do an npm install. Make sure to run this on a Mac or linux system.

As this is a side project, it's not possible from my side. Therefore it is an open source project, so anyone can put his effort into this.

**Comment by airbenich** [comment]
Take a look at: https://github.com/electron/electron-quick-start/issues/117#issuecomment-266417904

**Comment by techiedavid** [comment]
I had the same problem. I tried so many things that I'm not really sure what worked. But the last thing I did was updated the OS and removed nodejs and then install the version 14 of nodejs. That seemed to work.
