### ISSUE TITLE
Change touch actions

### ISSUE THREAD

**Issue by Patrickonzales** [airbenich/multiviewTouchControl#8]
Hello

This is an awesome tool. thanks for sharing this.

Is is possible to call different actions. So instead of a camera start a macro. that would be awesome to work with overlays.

another nice thing would be a shut down function at the very top left corner, to safely shut down the raspberry.

Thanks for your work

kind regards Patrick

**Comment by airbenich** [comment]
Hello Patrick,

You're welcome! Thats theoretically possible.
All touch actions are connected to the corresponding tasks in the renderer.js file:
https://github.com/airbenich/multiviewTouchControl/blob/master/renderer.js

There you can change the action there as you like. I just added the `mainswitcher.macroStart(macroIndex)` and `mainswitcher.macrostop()` method to the VideoSwitcher Class.

For restarting the raspberry that would be also possible. But the application would need root permissions to do that and that's a bit difficult.

Greetings,
Vivian

**Comment by Patrickonzales** [comment]
Hello Vivian

Thanks for your help.
I tried this, but it does not work.

How does the syntax work correctly? Isn't it mainswitcher.macroStart(5) to start the 6th Macro?
